#pragma once
#include "ascendc/host_api/tiling/template_argument.h"
ASCENDC_TPL_ARGS_DECL(FaFaNkNzVectorFp32V3,
  ASCENDC_TPL_UINT_DECL(ROW_TILES, ASCENDC_TPL_2_BW, ASCENDC_TPL_UI_LIST, 0));
ASCENDC_TPL_SEL(ASCENDC_TPL_ARGS_SEL(
  ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
  ASCENDC_TPL_UINT_SEL(ROW_TILES, ASCENDC_TPL_UI_LIST, 0)));
